### ISSUE TITLE
ReactApp: GraphXY default width causes the graph to overflow

### ISSUE THREAD

**Issue by hanak** [React-Automation-Studio/React-Automation-Studio#110]
**Problem**

When the property `width` is not set, it defaults to `100%`. This results into the following style at the top level `<div>`:
```
width: 100%;
margin: 8;
```
Width `100%` means width of the parent. However, impacts width of the content only: margin is not considered. Since the margin is set, the real width of the component is going to be `100% + 16` which is unlikely to be correct.

**Workaround**

Set the property width to `calc(100% - 16)`. While this prevent overflowing, it leaves a gap of 8 px surrounding the graph.

**Proposed Solution**

Add a property `m` and use it with to set the margin. Value uses spacing defined in the theme. If not supplied, default to 8 px regardless the spacing (the current behavior). This will keep backward compatibility intact while it allows one to prevent coping internal constants outside.

**Comment by wduckitt** [comment]
i have added a prop plotlyStyle so that the user can override the default style, fix is in V4.02
