### ISSUE TITLE
TextInput component can't handle waveform PV input

### ISSUE THREAD

**Issue by Tini4** [React-Automation-Studio/React-Automation-Studio#117]
## binaryWaveform from example (Style Guide/Compound Components/ArrayContainer)
I have a TextInput component that receives a waveform PV like in the documentation:
```js
<TextInput
  pv="$(device):binaryWaveform"
  macros={{ "$(device)": "testIOC" }}
  usePvLabel={true}
  debug={true}
/>
```
![image](https://github.com/React-Automation-Studio/React-Automation-Studio/assets/67708027/515e8f85-7650-4d3f-b6e4-9d08984165fd)
When I try to change the value (lets say the last 0 to a 1), this happens:
![image](https://github.com/React-Automation-Studio/React-Automation-Studio/assets/67708027/f4f2bf2d-0355-415f-a5c7-bca62928d480)
Nothing else seems to break, just the value is broken.

## waveform with characters
It is even worse with waveform PVs that hold characters.
The goal is to have TextInput component that receives a waveform PV with character array:
```js
<TextInput
  pv="$(DEVICE):RawTiff:FilePath"
  macros={{ "$(DEVICE)": props.device }}
  label={"Save path"}
  useStringValue={true}
  debug={true}
/>
```
![image](https://github.com/React-Automation-Studio/React-Automation-Studio/assets/67708027/97be8827-9ea3-4279-b387-105881ebb862)
When I try to to change the value (lets say to /tempa), this happens:
![image](https://github.com/React-Automation-Studio/React-Automation-Studio/assets/67708027/70bed753-f503-4de8-8bb3-e48242b105f1)
And I get this error in the console:
`Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components`
After doing some debugging, I found out is that `pv` variable in EpicsPV.js(React-Automation-Studio/ReactApp/src/components/SystemComponents/EpicsPV.js) gets value set to `undefined` when you try to update it.
The TextOutput component holding the same PV as TextInput also breaks the same way, when you try to update the value with TextInput.
Displaying the PV works fine, but something goes wrong when updating it.
The waveform with characters is fine once you refresh the page and displays the updated value, but breaks again as soon as you try to change it.

**Comment by wduckitt** [comment]
Interesting, it appears to be displaying the ascii code of decimal value entered. I'll investigate it further.

**Comment by wduckitt** [comment]
I don't believe this is a bug, perhaps the author of the documentation could have phrased the use cases better.


The the intention was that the array container should be used which wraps multiple text inputs to each of the indivual array entry,
If one enters the value in the indexed textinput the correct value is stored in the waveform. 


Yes, one can use a standalone TextInput and TextOutput component to display the raw values of a waveform, and in the case of TextInput you can edit  the string as you have show above, but there is no mechanism availble to convert that text string to epics waverform type, in this case it seems to write the ascii values into the stored array.

**Comment by wduckitt** [comment]
My proposal is the documentaion much be updated to prevent your unintentional use case

**Comment by Tini4** [comment]
I see, but this still doesn't explain the 2nd case.
When I try to use TextInput for waveform with character array, the component breaks with the console error I provided before.
Do you want me to open a separate issue for that?
Like I said, in the character array case the EPICS PV value is written correctly, but something in the UI breaks.

**Comment by Tini4** [comment]
What I am trying to do is to recreate AreaDetector GUI in RAS. I have a lot of PVs that hold file paths and different configurations that are saved as waveform character arrays.
If TextInput issue can't be resolved, what component should I use for editing waveforms with character arrays?

**Comment by wduckitt** [comment]
If it has something  to do with legacy code and you need to handle characters stored as waveform  the nI suggest you create a new custom component for this based on the PV example in styleguide.

**Comment by Tini4** [comment]
It is a standard solution for AreaDetector (http://areadetector.github.io/areaDetector/ADCore/medm.html).
File path can be a lot longer than 40 characters, so waveform of characters is used.

**Comment by Tini4** [comment]
I can try implementation with PV example, but the TextOutput still breaks on value change, the same way as TextInput does. The value is saved correctly, but the UI side breaks (React returns an error), so if you fix that everything might work. Do I open another issue for that?

**Comment by Tini4** [comment]
I opened a new issue for the UI breaking on input in case of waveform with char array. The documentation update is fine for waveform with integers, since the UI doesn't break.
