### ISSUE TITLE
ReactApp: Fix issues reported by npm audit

### ISSUE THREAD

**Issue by hanak** [React-Automation-Studio/React-Automation-Studio#41]
Problem: npm audit report known issues/vulnerabilities. That number of issues grows are time moves one. Usually, a solution is an upgrade of a package or packages.

Solution: Upgrade packages as recommended by npm audit and adjust source code in case of incompatibility.

**Comment by wduckitt** [comment]
If you follow this post

https://github.com/facebook/create-react-app/issues/11174

and move react scripts to devDependencies, and then run npm audit --production, then we get no vulnerabilities
