### ISSUE TITLE
Update or generate poetry.lock through docker

### ISSUE THREAD

**Issue by wduckitt** [React-Automation-Studio/React-Automation-Studio#74]
I like the new addtion of poetry. I do feel though that the lock file should be generated using the Python docker image that runs the pvServer as apposed to another virtual env somewhere else. Perhaps whoever maintains the dependancies of the pvServer in future can simply temporarily mount the pvServer folder in the container and then generate a new lock file that persists in the mono repo.

**Comment by hanak** [comment]
The item was marked as to be resolved through #81. As a consequence, it should be assigned to the same milestone (V3.2.0) as #81.
