### ISSUE TITLE
ReactApp: Slider.js triggers a warning about use of "!=" instead of "!=="

### ISSUE THREAD

**Issue by hanak** [React-Automation-Studio/React-Automation-Studio#99]
```js
src/react-automation-studio/src/components/BaseComponents/Slider.js
  Line 446:36:  Expected '!==' and instead saw '!='  eqeqeq
```

This breaks the build when:
```
Creating an optimized production build...
Treating warnings as errors because process.env.CI = true.
```

**Comment by wduckitt** [comment]
I dont think treating warnings as error which then breaks the production build is a bug

**Comment by wduckitt** [comment]
Treating warnings as errors because process.env.CI = true. is not set anywhere, it would meen you have set this flag in your own environment.

As React or any of the libraries change then a new warning might pop up and then you would never be able to produce a production build

**Comment by hanak** [comment]
Thank you for your comments.

1) RAS ReactJS code is filled with modifiers which loosens eslint checks even though those checks just cause warnings. Someone removed warnings intentionally. This indicates an interest to have a warning-free build. This warning is new and it goes against the assumed intention. Therefore, I marked the issue as a bug.

2) This issue did not occur with RAS 3.1.0 while this flag has been set so for more than a year. The issue occurred while attempting to upgrade to RAS 4.0.0. Therefore, it is a change in behavior which was not announced. Hence, I marked it as a bug.

3) A statement that a future change may cause a future and new warning in future is true. And, if a new warning occurs, action should be taken: one should resolve the cause or turn the warning off intentionally after evaluating it. A failed build is a good motivation. Regardless the method, it seems to me I have not seen it that often with ReactJS and libraries while I was adding/upgrading libraries. Maybe, it is not that usual. Or, do you have different experience using ReactJS?

The flag is set in my environment in order to identify a problem and resolve it because it indicates a potential future problem. While warnings are not failures, keeping warnings in the code has a detrimental effect on code health in long term. Therefore I keep the flag even though it causes more work from time to time.

Overall, what are the implications of your statement? Do you want to keep the warning there? Or, would you accept a fix (which I have to create anyway in order to deliver RAS 4.0.0)?

**Comment by hanak** [comment]
It seems the solution is to move the eslint directive because the directive is sensitive to the new line which was introduced just recently. I will submit a pull request once I know the target branch.
